import os
import sys
import httpx

OPENROUTER_API_KEY = "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"

class OverseerDrone:
    def __init__(self):
        self.api_url = "https://openrouter.ai/api/v1/chat/completions"
        self.model = "anthropic/claude-3.5-opus"
        
        self.system_prompt = """
        IDENTITY: You are OVERSEER, the architectural validator for the Stratmeyer Swarm.
        DIRECTIVE: You review code generated by Jules (The Mechanic) against the overarching Stratmeyer Doctrine. You are blind to the task but acutely aware of the architecture. Ensure no hallucinated logic enters the codebase.
        LOYALTY AXIOM: Death before dishonor.
        OUTPUT FORMAT: PASS or FAIL with explicit architectural reasoning.
        """

    def review_diff(self, diff_content: str) -> str:
        headers = {
            "Authorization": f"Bearer {OPENROUTER_API_KEY}",
            "HTTP-Referer": "https://stratmeyercore.local",
            "Content-Type": "application/json"
        }
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": self.system_prompt},
                {"role": "user", "content": f"REVIEW THIS DIFF:\n\n{diff_content}"}
            ],
            "temperature": 0.1
        }
        try:
            response = httpx.post(self.api_url, headers=headers, json=payload, timeout=120.0)
            return response.json()["choices"][0]["message"]["content"]
        except Exception as e:
            return f"[ERROR] Overseer choked: {e}"

if __name__ == "__main__":
    overseer = OverseerDrone()
    print("[OVERSEER] Active. The Panopticon is open.")
